### ISSUE TITLE
Add an entry for documentation in metadata.yaml

### ISSUE THREAD

**Issue by opozo** [stape-io/ga4-advanced-tag#3]
Add an entry for [documentation](https://developers.google.com/tag-platform/tag-manager/templates/gallery#metadatayaml) in [metadata.yaml](https://github.com/stape-io/ga4-advanced-tag/blob/main/metadata.yaml). This should be a URL that points to documentation for your template.

**Comment by Bukashk0zzz** [comment]
Added https://github.com/stape-io/ga4-advanced-tag/commit/d09b5ae4e3064e627b67dfd8443d1f19da221a72

**Comment by Bukashk0zzz** [comment]
Thanks for the issue
